package au.com.woolworths.village.sdk.model

/**
 * Types of [QRCode]s that can be generated by the API.
 */
enum class QRCodePaymentReferenceType {
    /** Associated to a Payment Request */
    PAYMENT_REQUEST,

    /** Associated to a [PaymentSession] */
    PAYMENT_SESSION
}