package au.com.wpay.sdk.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonNames

/**
 * Types of [QRCode]s that can be generated by the API.
 */
@Suppress("EXPERIMENTAL_API_USAGE")
@Serializable
enum class QRCodePaymentReferenceType {
    /** Associated to a Payment Request */
    @SerialName("PAYMENT_REQUEST")
    @JsonNames("payment_request")
    PAYMENT_REQUEST,

    /** Associated to a [PaymentSession] */
    @SerialName("PAYMENT_SESSION")
    @JsonNames("payment_session")
    PAYMENT_SESSION
}
