#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIBasket.h"
#import "OAICustomerTransactionDetailAllOf.h"
#import "OAICustomerTransactionSummary.h"
#import "OAICustomerTransactionSummaryAllOfInstruments.h"
@protocol OAIBasket;
@class OAIBasket;
@protocol OAICustomerTransactionDetailAllOf;
@class OAICustomerTransactionDetailAllOf;
@protocol OAICustomerTransactionSummary;
@class OAICustomerTransactionSummary;
@protocol OAICustomerTransactionSummaryAllOfInstruments;
@class OAICustomerTransactionSummaryAllOfInstruments;



@protocol OAICustomerTransactionDetail
@end

@interface OAICustomerTransactionDetail : OAICustomerTransactionSummary


@property(nonatomic) OAIBasket* basket;

@end
