#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIGetCustomerPaymentInstrumentsResultsDataCreditCards.h"
#import "OAIGetCustomerPaymentInstrumentsResultsDataGiftCards.h"
@protocol OAIGetCustomerPaymentInstrumentsResultsDataCreditCards;
@class OAIGetCustomerPaymentInstrumentsResultsDataCreditCards;
@protocol OAIGetCustomerPaymentInstrumentsResultsDataGiftCards;
@class OAIGetCustomerPaymentInstrumentsResultsDataGiftCards;



@protocol OAIGetCustomerPaymentInstrumentsResultsData
@end

@interface OAIGetCustomerPaymentInstrumentsResultsData : OAIObject


@property(nonatomic) NSArray<OAIGetCustomerPaymentInstrumentsResultsDataCreditCards>* creditCards;

@property(nonatomic) NSArray<OAIGetCustomerPaymentInstrumentsResultsDataGiftCards>* giftCards;

@end
