#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIBasket.h"
#import "OAIMerchantPayload.h"
#import "OAIMerchantPaymentDetailAllOf.h"
#import "OAIMerchantPaymentSummary.h"
#import "OAIPosPayload.h"
@protocol OAIBasket;
@class OAIBasket;
@protocol OAIMerchantPayload;
@class OAIMerchantPayload;
@protocol OAIMerchantPaymentDetailAllOf;
@class OAIMerchantPaymentDetailAllOf;
@protocol OAIMerchantPaymentSummary;
@class OAIMerchantPaymentSummary;
@protocol OAIPosPayload;
@class OAIPosPayload;



@protocol OAIMerchantPaymentDetail
@end

@interface OAIMerchantPaymentDetail : OAIMerchantPaymentSummary


@property(nonatomic) OAIBasket* basket;

@property(nonatomic) OAIPosPayload* posPayload;

@property(nonatomic) OAIMerchantPayload* merchantPayload;

@end
