#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Village Wallet
* APIs for Village Wallet
*
* The version of the OpenAPI document: 0.0.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAICommonTransactionSummary.h"
#import "OAIMerchantTransactionSummaryAllOf.h"
@protocol OAICommonTransactionSummary;
@class OAICommonTransactionSummary;
@protocol OAIMerchantTransactionSummaryAllOf;
@class OAIMerchantTransactionSummaryAllOf;



@protocol OAIMerchantTransactionSummary
@end

@interface OAIMerchantTransactionSummary : OAICommonTransactionSummary

/* The ID of the wallet associated with this transaction 
 */
@property(nonatomic) NSString* walletId;

@end
