/*
 * Village Wallet
 * APIs for Village Wallet
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.woolworths.village.sdk.dto;

import java.util.Objects;
import java.util.Arrays;
import au.com.woolworths.village.sdk.dto.GetCustomerPaymentInstrumentsResultsDataCreditCards;
import au.com.woolworths.village.sdk.dto.GetCustomerPaymentInstrumentsResultsDataGiftCards;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Mandatory data object containing response
 */
@ApiModel(description = "Mandatory data object containing response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-30T10:56:50.564+10:00[Australia/Melbourne]")
public class GetCustomerPaymentInstrumentsResultsData {
  public static final String SERIALIZED_NAME_CREDIT_CARDS = "creditCards";
  @SerializedName(SERIALIZED_NAME_CREDIT_CARDS)
  private List<GetCustomerPaymentInstrumentsResultsDataCreditCards> creditCards = new ArrayList<GetCustomerPaymentInstrumentsResultsDataCreditCards>();

  public static final String SERIALIZED_NAME_GIFT_CARDS = "giftCards";
  @SerializedName(SERIALIZED_NAME_GIFT_CARDS)
  private List<GetCustomerPaymentInstrumentsResultsDataGiftCards> giftCards = new ArrayList<GetCustomerPaymentInstrumentsResultsDataGiftCards>();


  public GetCustomerPaymentInstrumentsResultsData creditCards(List<GetCustomerPaymentInstrumentsResultsDataCreditCards> creditCards) {
    
    this.creditCards = creditCards;
    return this;
  }

  public GetCustomerPaymentInstrumentsResultsData addCreditCardsItem(GetCustomerPaymentInstrumentsResultsDataCreditCards creditCardsItem) {
    this.creditCards.add(creditCardsItem);
    return this;
  }

   /**
   * Get creditCards
   * @return creditCards
  **/
  @ApiModelProperty(required = true, value = "")

  public List<GetCustomerPaymentInstrumentsResultsDataCreditCards> getCreditCards() {
    return creditCards;
  }


  public void setCreditCards(List<GetCustomerPaymentInstrumentsResultsDataCreditCards> creditCards) {
    this.creditCards = creditCards;
  }


  public GetCustomerPaymentInstrumentsResultsData giftCards(List<GetCustomerPaymentInstrumentsResultsDataGiftCards> giftCards) {
    
    this.giftCards = giftCards;
    return this;
  }

  public GetCustomerPaymentInstrumentsResultsData addGiftCardsItem(GetCustomerPaymentInstrumentsResultsDataGiftCards giftCardsItem) {
    this.giftCards.add(giftCardsItem);
    return this;
  }

   /**
   * Get giftCards
   * @return giftCards
  **/
  @ApiModelProperty(required = true, value = "")

  public List<GetCustomerPaymentInstrumentsResultsDataGiftCards> getGiftCards() {
    return giftCards;
  }


  public void setGiftCards(List<GetCustomerPaymentInstrumentsResultsDataGiftCards> giftCards) {
    this.giftCards = giftCards;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCustomerPaymentInstrumentsResultsData getCustomerPaymentInstrumentsResultsData = (GetCustomerPaymentInstrumentsResultsData) o;
    return Objects.equals(this.creditCards, getCustomerPaymentInstrumentsResultsData.creditCards) &&
        Objects.equals(this.giftCards, getCustomerPaymentInstrumentsResultsData.giftCards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditCards, giftCards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCustomerPaymentInstrumentsResultsData {\n");
    sb.append("    creditCards: ").append(toIndentedString(creditCards)).append("\n");
    sb.append("    giftCards: ").append(toIndentedString(giftCards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

