/*
 * Village Wallet
 * APIs for Village Wallet
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.woolworths.village.sdk.dto;

import java.util.Objects;
import java.util.Arrays;
import au.com.woolworths.village.sdk.dto.CommonPaymentBase;
import au.com.woolworths.village.sdk.dto.MerchantPaymentSummaryAllOf;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Summary information for a single payment request
 */
@ApiModel(description = "Summary information for a single payment request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-30T15:44:28.835+10:00[Australia/Melbourne]")
public class MerchantPaymentSummary extends CommonPaymentBase {
  public static final String SERIALIZED_NAME_USES_REMAINING = "usesRemaining";
  @SerializedName(SERIALIZED_NAME_USES_REMAINING)
  private Integer usesRemaining;

  public static final String SERIALIZED_NAME_EXPIRY_TIME = "expiryTime";
  @SerializedName(SERIALIZED_NAME_EXPIRY_TIME)
  private String expiryTime;

  public static final String SERIALIZED_NAME_SPECIFIC_WALLET_ID = "specificWalletId";
  @SerializedName(SERIALIZED_NAME_SPECIFIC_WALLET_ID)
  private String specificWalletId;


  public MerchantPaymentSummary usesRemaining(Integer usesRemaining) {
    
    this.usesRemaining = usesRemaining;
    return this;
  }

   /**
   * The number of times that the payment request can be used to create a payment. If basent then request can be used an unlimited number of times
   * minimum: 0
   * @return usesRemaining
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of times that the payment request can be used to create a payment. If basent then request can be used an unlimited number of times")

  public Integer getUsesRemaining() {
    return usesRemaining;
  }


  public void setUsesRemaining(Integer usesRemaining) {
    this.usesRemaining = usesRemaining;
  }


  public MerchantPaymentSummary expiryTime(String expiryTime) {
    
    this.expiryTime = expiryTime;
    return this;
  }

   /**
   * The ISO date/time for when the payment request will expire and become unusable for payments.  If absent then the payment request will not expire until it is deleted
   * @return expiryTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ISO date/time for when the payment request will expire and become unusable for payments.  If absent then the payment request will not expire until it is deleted")

  public String getExpiryTime() {
    return expiryTime;
  }


  public void setExpiryTime(String expiryTime) {
    this.expiryTime = expiryTime;
  }


  public MerchantPaymentSummary specificWalletId(String specificWalletId) {
    
    this.specificWalletId = specificWalletId;
    return this;
  }

   /**
   * The ID of a specific wallet for which the payment is intended.  If present then the payment can only be used by the intended wallet.  If absent then any wallet can create a payment against the payment request
   * @return specificWalletId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of a specific wallet for which the payment is intended.  If present then the payment can only be used by the intended wallet.  If absent then any wallet can create a payment against the payment request")

  public String getSpecificWalletId() {
    return specificWalletId;
  }


  public void setSpecificWalletId(String specificWalletId) {
    this.specificWalletId = specificWalletId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantPaymentSummary merchantPaymentSummary = (MerchantPaymentSummary) o;
    return Objects.equals(this.usesRemaining, merchantPaymentSummary.usesRemaining) &&
        Objects.equals(this.expiryTime, merchantPaymentSummary.expiryTime) &&
        Objects.equals(this.specificWalletId, merchantPaymentSummary.specificWalletId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usesRemaining, expiryTime, specificWalletId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantPaymentSummary {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    usesRemaining: ").append(toIndentedString(usesRemaining)).append("\n");
    sb.append("    expiryTime: ").append(toIndentedString(expiryTime)).append("\n");
    sb.append("    specificWalletId: ").append(toIndentedString(specificWalletId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

