name: 'Build'

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set git config
        run: |
           git config user.name github-actions
           git config user.email github-actions@github.com

      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Unit tests
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: test

      - name: Update docs
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          ./gradlew dokkaHtml
          git add sdk/docs/
          git commit -m 'Updated docs' || echo "No changes to docs"
          git push

      - name: Tag
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./scripts/tag.sh
        env:
          GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}

      - name: Push changes
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git push
          git push --tags
